spring:
  application:
    name: dog-management-system
  
  # Configuración de la base de datos H2
  datasource:
    url: jdbc:h2:mem:dogdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # Configuración JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: true
  
  # Configuración para inicialización de datos
  sql:
    init:
      mode: always
  
  # Configuración H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

# Configuración del servidor
server:
  port: 8080

# Configuración de Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Configuración de OpenAPI/Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    displayRequestDuration: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# Configuración de logging
logging:
  level:
    com.dogapp: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Información de la aplicación
info:
  app:
    name: Dog Management System
    description: Sistema de gestión de perros con microservicios
    version: 1.0.0
    developer: Tu Nombre
    contact: tu.email@ejemplo.com 